In [1]:
import pandas as pd
import numpy as np

In [6]:
main_path = "/home/sebastian/github/SpecialProblem_Salo/drone_irrigation_vrep/src/data_base/paths_energy/feat_pathv12_nuevo.csv"
pd_data = pd.read_csv(main_path)

In [16]:
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2335 entries, 0 to 2334
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   path_num               2335 non-null   int64
 1   missing_points         2335 non-null   int64
 2   teo_point_time         2335 non-null   int64
 3   sim_drone_time         2335 non-null   float64
 4   teo_point_dist         2335 non-null   float64
 5   sim_point_dist         2335 non-null   float64
 6   teo_Xdist              2335 non-null   float64
 7   teo_Ydist              2335 non-null   float64
 8   sim_Xdist              2335 non-null   float64
 9   sim_Ydist              2335 non-null   float64
 10  avg_error_target_dist  2335 non-null   float64
 11  teo_point_vel          2335 non-null   float64
 12  Energy                 2335 non-null   float64
 13  avg_energy             2335 non-null   float64
dtypes: float64(11), int64(3)
memory usage: 255.5 KB

In [7]:
pd_data.head()

,path_num,missing_points,teo_point_time,sim_drone_time,teo_point_dist,sim_point_dist,teo_Xdist,teo_Ydist,sim_Xdist,sim_Ydist,avg_error_target_dist,teo_point_vel,Energy,avg_energy
0,1,7,91,89.300003,5.656854,5.446446,4.0,4.0,3.851872,3.850145,0.097609,0.062163,3.547184e+06,373905.984820
1,1,6,90,86.850006,3.000000,3.171659,0.0,3.0,0.537618,3.019579,0.054447,0.033333,3.293748e+06,353126.888948
2,1,4,70,68.600006,5.000000,4.828957,3.0,4.0,2.877582,3.841778,0.107537,0.071429,2.346655e+06,284573.658456
3,1,3,98,94.499985,3.000000,3.174537,3.0,0.0,2.962148,0.679134,0.044139,0.030612,3.630906e+06,376507.424073
4,1,2,95,91.049988,3.000000,2.965050,0.0,3.0,0.399833,2.823458,0.041145,0.031579,3.397217e+06,360104.282185

In [12]:
eps = 5
pd_strange = pd_data[(pd_data["sim_point_dist"]-pd_data["teo_point_dist"]) > eps]
pd_good = pd_data[(pd_data["sim_point_dist"]-pd_data["teo_point_dist"]) < eps]

In [18]:
pd_strange.head()

,path_num,missing_points,teo_point_time,sim_drone_time,teo_point_dist,sim_point_dist,teo_Xdist,teo_Ydist,sim_Xdist,sim_Ydist,avg_error_target_dist,teo_point_vel,Energy,avg_energy
6,2,8,87,98.400002,9.848858,27.553946,9.0,4.0,24.934430,11.712182,0.115240,0.113205,4.183034e+06,424722.797394
21,4,8,78,89.300003,9.848858,27.853925,9.0,4.0,22.737664,15.649199,0.118887,0.126267,3.176907e+06,355189.018858
27,5,8,73,84.699997,12.727922,40.673401,9.0,9.0,28.762135,28.488719,0.190326,0.174355,3.068491e+06,356704.799511
34,6,8,79,91.099998,10.630146,23.663586,7.0,8.0,18.642441,13.717880,0.130490,0.134559,2.996434e+06,343714.533681
42,7,8,99,109.500000,6.082763,15.737917,1.0,6.0,6.730322,13.797989,0.056415,0.061442,3.228841e+06,350216.941680

In [17]:
pd_good.head()

,path_num,missing_points,teo_point_time,sim_drone_time,teo_point_dist,sim_point_dist,teo_Xdist,teo_Ydist,sim_Xdist,sim_Ydist,avg_error_target_dist,teo_point_vel,Energy,avg_energy
0,1,7,91,89.300003,5.656854,5.446446,4.0,4.0,3.851872,3.850145,0.097609,0.062163,3.547184e+06,373905.984820
1,1,6,90,86.850006,3.000000,3.171659,0.0,3.0,0.537618,3.019579,0.054447,0.033333,3.293748e+06,353126.888948
2,1,4,70,68.600006,5.000000,4.828957,3.0,4.0,2.877582,3.841778,0.107537,0.071429,2.346655e+06,284573.658456
3,1,3,98,94.499985,3.000000,3.174537,3.0,0.0,2.962148,0.679134,0.044139,0.030612,3.630906e+06,376507.424073
4,1,2,95,91.049988,3.000000,2.965050,0.0,3.0,0.399833,2.823458,0.041145,0.031579,3.397217e+06,360104.282185

In [19]:
pd_strange.describe()

,path_num,missing_points,teo_point_time,sim_drone_time,teo_point_dist,sim_point_dist,teo_Xdist,teo_Ydist,sim_Xdist,sim_Ydist,avg_error_target_dist,teo_point_vel,Energy,avg_energy
count,303.000000,303.000000,303.00000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,303.000000,3.030000e+02,303.000000
mean,162.669967,7.851485,83.69967,157.626733,8.505599,25.021383,5.488449,5.716172,16.659961,16.348653,0.098592,0.103240,1.590576e+06,216399.053857
std,93.550160,0.383072,8.81406,66.626848,3.178153,7.764366,3.156885,3.116709,7.916153,7.588078,0.047674,0.041194,6.972714e+05,61072.910014
min,2.000000,7.000000,70.00000,81.349998,1.414214,7.533399,0.000000,0.000000,3.044303,3.014846,0.012078,0.014285,5.112397e+05,102247.933587
25%,81.500000,8.000000,76.00000,104.025002,6.403124,19.795631,2.000000,3.000000,9.907248,9.932359,0.066423,0.075682,1.145107e+06,175608.115679
50%,161.000000,8.000000,83.00000,133.550003,9.055385,25.622303,6.000000,6.000000,17.174740,16.703808,0.093742,0.104195,1.355446e+06,196911.586988
75%,244.000000,8.000000,92.00000,207.424995,10.535226,30.384199,8.000000,9.000000,23.726162,23.012423,0.121915,0.130187,1.695006e+06,230228.682254
max,326.000000,9.000000,99.00000,408.350006,14.142136,42.189120,10.000000,10.000000,29.934992,29.876466,0.266186,0.191110,4.613425e+06,448095.430217

In [20]:
pd_good.describe()

,path_num,missing_points,teo_point_time,sim_drone_time,teo_point_dist,sim_point_dist,teo_Xdist,teo_Ydist,sim_Xdist,sim_Ydist,avg_error_target_dist,teo_point_vel,Energy,avg_energy
count,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2032.000000,2.032000e+03,2032.000000
mean,170.346949,3.942421,84.677657,141.492569,4.576175,4.678029,2.961614,2.763287,3.058915,2.851982,0.067169,0.054695,1.334514e+06,190853.568130
std,95.084358,2.003476,8.641838,66.061890,2.919410,2.943587,2.662633,2.443366,2.590222,2.379981,0.049191,0.035667,5.656571e+05,51446.076278
min,1.000000,1.000000,70.000000,64.100037,1.000000,0.629151,0.000000,0.000000,0.000021,0.000325,0.007178,0.010101,2.633366e+05,65834.146272
25%,88.000000,2.000000,77.000000,89.437508,2.000000,2.066079,1.000000,1.000000,0.951520,0.933802,0.031419,0.023810,9.853344e+05,158172.406134
50%,174.000000,4.000000,85.000000,113.199997,4.242641,4.190188,2.000000,2.000000,2.093302,2.079094,0.054813,0.047879,1.175318e+06,177468.805562
75%,254.000000,6.000000,92.000000,191.250031,7.000000,6.867840,4.000000,4.000000,4.204998,3.985559,0.089538,0.078002,1.422181e+06,203362.155514
max,326.000000,8.000000,99.000000,490.649902,14.142136,18.527587,10.000000,10.000000,13.973150,12.853641,0.432595,0.181827,4.137702e+06,419719.132654